# System States
STATE_INIT = "INIT"
STATE_RUNNING = "RUNNING"
STATE_PAUSED = "PAUSED"
STATE_ERROR = "ERROR"
STATE_STOPPED = "STOPPED"

# Standard Event Topics
EVENT_TICK = "TICK"
EVENT_UI_UPDATED = "UI_UPDATED"
EVENT_ACTION_REQUESTED = "ACTION_REQUESTED"
EVENT_STATE_CHANGED = "STATE_CHANGED"
