from __future__ import annotations

TRANSPORT_HEALTH = "TRANSPORT_HEALTH"
TRANSPORT_HEALTHY = "TRANSPORT_HEALTHY"
TRANSPORT_UNHEALTHY = "TRANSPORT_UNHEALTHY"
TRANSPORT_RESTART_REQUEST = "TRANSPORT_RESTART_REQUEST"
TRANSPORT_RECOVERED = "TRANSPORT_RECOVERED"
TRANSPORT_RECOVERY_FAILED = "TRANSPORT_RECOVERY_FAILED"
